spring:
  application:
    name: petopia

  datasource:
    url: jdbc:postgresql://localhost:5432/petopia
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8000/realms/api.knox.gb.net/protocol/openid-connect/certs"

springdoc:
  swagger-ui:
    operations-sorter: alpha

server:
  servlet:
    context-path: /petopia