spring:
  application:
    name: petopia

  datasource:
    url: jdbc:postgresql://localhost:5432/petopia
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /petopia